vich_uploader:
    db_driver: orm

    mappings:
        brand_images:
            uri_prefix: /images/brand_images
            upload_destination: '%kernel.project_dir%/public/images/brand_images'

        product_images:
            uri_prefix: /images/product_images
            upload_destination: '%kernel.project_dir%/public/images/product_images'
